// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeIoISG_R13kXdfMFKXxTrH7EFqKcr9rc',
    appId: '1:854239204594:web:5ead9995f30ee0eae0ac6b',
    messagingSenderId: '854239204594',
    projectId: 'flash-chat-1bb6f',
    authDomain: 'flash-chat-1bb6f.firebaseapp.com',
    storageBucket: 'flash-chat-1bb6f.appspot.com',
    measurementId: 'G-3VHV2Z1625',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4ZlBzzRRlsKk_rdITc30mKoB1Tm4csdk',
    appId: '1:854239204594:android:6ed56745891d5bd9e0ac6b',
    messagingSenderId: '854239204594',
    projectId: 'flash-chat-1bb6f',
    storageBucket: 'flash-chat-1bb6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSLK4RVvvQhbvzvSGnanAExuonDm74gBU',
    appId: '1:854239204594:ios:6dc3c9a67a2a1721e0ac6b',
    messagingSenderId: '854239204594',
    projectId: 'flash-chat-1bb6f',
    storageBucket: 'flash-chat-1bb6f.appspot.com',
    iosClientId: '854239204594-5tltfue8dgh6vqo2tp48rqlmhvotog6n.apps.googleusercontent.com',
    iosBundleId: 'com.raghavbhatia8.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSLK4RVvvQhbvzvSGnanAExuonDm74gBU',
    appId: '1:854239204594:ios:6dc3c9a67a2a1721e0ac6b',
    messagingSenderId: '854239204594',
    projectId: 'flash-chat-1bb6f',
    storageBucket: 'flash-chat-1bb6f.appspot.com',
    iosClientId: '854239204594-5tltfue8dgh6vqo2tp48rqlmhvotog6n.apps.googleusercontent.com',
    iosBundleId: 'com.raghavbhatia8.flashChat',
  );
}
